canonical/cos-proxy-operator

- .github/workflows/run_tests.yaml
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- src/charm.py
This commit imports and renames the latest Prometheus library
from the Prometheus Operator github repository. Note that
this version of the Prometheus library has not yet been
released to Charmhub since charmcraft as yet does not
support library name changes. Creating a new library with
a different name is not advised since it is expected that
a specific library will always retain the same library ID.
> Imported and rename latest Prometheus library

- requirements.txt
Pulling a Jinja v3.x makes `charmcraft pack` very unhappy.
> Pin Jinja to version 2

- .gitignore
- README.md
- charmcraft.yaml
- metadata.yaml
- src/charm.py
- tox.ini
Align `cos-proxy` with the existing usage of `cos-tool` by packing `nrpe_exporter`.
Closes #20
> Pack nrpe_exporter as part of the charm

- lib/charms/nrpe_exporter/v0/nrpe_exporter.py
Use unit.name in the alert rule generation, not plain 'nrpe', so it's serializable
> Use unit.name in the alert rule generation, not plain 'nrpe'

- charmcraft.yaml
- lib/charms/grafana_k8s/v0/grafana_dashboard.py
- lib/charms/nrpe_exporter/v0/nrpe_exporter.py
- lib/charms/observability_libs/v0/juju_topology.py
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- lib/charms/vector/v0/vector.py
- metadata.yaml
- src/charm.py
- tests/unit/test_charm.py
`cos-proxy` did not previously have any support for logging in reactive/machine charms over the `filebeat` interface.
In addition, the output from NRPE commands was not visible, so operators had to manually check on failed jobs.
Use [vector](https://vector.dev/) to provide a filebeat-compatible ingestor.
Add support for remote Loki relations as a "sink", and manipulate the input from filebeat and nrpe-exporter journald logs using vector remap language before pushing it off to Loki.
Vector is able to use a lookaside "enrichment table" to provide ancillary data. Since the NRPE exporter itself is not aware of (nor has reason to be) juju topology, use the ip address and command concatenated as a composite key for enrichment table lookups.
Closes #30 
Deploy a machine charm. Deploy and relate …
> Add support for logging 

- README.md
- lib/charms/nrpe_exporter/v0/nrpe_exporter.py
- lib/charms/observability_libs/v0/juju_topology.py
- lib/charms/operator_libs_linux/v1/systemd.py
- lib/charms/vector/v0/vector.py
- src/charm.py
PyYAML gets confused when serializing the Vector config, and it's a multi-line YAML string with newlines (as literal `\n`), which may case vector to try to interpret a commented line. Move the comment.
If Vector cannot reach a Loki sink, it may not start (or fail to restart). Try to connect to the endpoints and, if they cannot be reached, go into `BlockedStatus` and skip writing the new config so it stays up.
Add an `absent_over_time` check to the automatic NRPE alerts so "Schroedinger's metrics" still alert also.
> Catch potential error conditions

- charmcraft.yaml
- metadata.yaml
this pr solve issue #43 
Adds support for Ubuntu 22.04 (Jammy Jellyfish) in charmcraft.yaml and metadata.yaml:
- Adds a build-on section for Ubuntu 22.04.
- Adds a run-on section for Ubuntu 22.04.
- Updates series in metadata.yaml to include jammy.
- run charmcraft pack
- deploy cos-proxy_ubuntu-22.04-amd64.charm
- Added support for Ubuntu 22.04 (Jammy Jellyfish) in charmcraft.yaml and metadata.yaml.
- Updated series field in metadata.yaml to include jammy.
> add build for jammy

- lib/charms/grafana_k8s/v0/grafana_dashboard.py
- lib/charms/operator_libs_linux/v0/apt.py
- src/charm.py
- tests/unit/test_charm.py
Log an error if a key can't be found when removing a dashboard (if more than one exporter is related, the `event.app.name` will be the same, and the first relation-broken will purge it, as these seem to fire more than once in subordinates).
`prometheus-ceph-exporter` sends dashboards with `None` as explicit templating keys, which passes (theoretically) since the key exists, but `None` is not iterable. Add explicit `None` checks.
Purge `rsyslog` since it isn't used at all or useful in the proxy, and may cause the disk to fill up.
Closes #46
Closes #47 
Closes #48
> Remove rsyslog, handle empty keys on removal and in prometheus-ceph-exporter dashboards better

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
`requests` may throw a `ConnectionResetError` when attempting to read the response inside a contextmanager, and we should also catch that.
Ensure that all args are converted when logging. And trim the regexp down to only capture topology labels (for Grafana dashboards)
Catch more exception types, only capture 'juju_' labels to make execution faster
> Catch more exception types, only capture 'juju_' labels to make execution faster

- lib/charms/grafana_k8s/v0/grafana_dashboard.py
- tests/unit/test_charm.py
Grafana dashboards may use `{{ variable }}` for formatting some fields, particularly legends, as Golang templates use the same formatting as Jinja.
Closes #61 
Closes #62 
Don't substitute `{{ host }}`, leave undefined variables in the Jinja environment alone.
Add test cases.
Use jinja2.DebugUndefined to leave unspecified template variables
> Use jinja2.DebugUndefined to leave unspecified template variables

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
Machines managed by Juju in MAAS _may_ be named `juju...`, which causes the prior regex to potentially match something such as `some_metric{host="model:jujulxd...", juju_application="foo", ...}` to accidentally swallow the whole thing.
Restrict it so it must start with `{` or `,` and be followed with `_[amu].*?` (`application|model|model_uuid|unit`) to minimize this risk.
Use a stricter regex for label matching for MAAS
> Use a stricter regex for label matching for MAAS

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
There was a risk of the previous capture, with `ceph-mon`, returning values such as:
```json
{
"targets": [
"10.95.155.32:9283"
],
"labels": {
"juju_model": "microk8s",
"juju_model_uuid": "ce085f22-7205-474e-8d1e-36a7c5c20a9a",
"juju_application": "ceph-mon",
"juju_unit": "ceph-mon/1",
"host": "10.95.155.32",
"dns_name": "eth2.juju-c20a9a-2-lxd-0.van3",
"juju-c20a9a-2-lxd-0\",hostname": "juju-c20a9a-2-lxd-0",
"juju-c20a9a-3-lxd-0\",hostname": "juju-c20a9a-3-lxd-0",
"juju-c20a9a-1-lxd-0\",hostname": "juju-c20a9a-1-lxd-0",
"juju-c20a9a-0-lxd-0\",hostname": "juju-c20a9a-0-lxd-0",
"juju-c20a9a-1-lxd-1\",hostname": "juju-c20a9a-1-lxd-1",
"juju-c20a9a-2-lxd-1\",hostname": "juju-c20a9a-2-lxd-1"
}
}
```
While the last patch covered this, we can be even stricter. 
Be even stricter and enforce a …
> Be even stricter and enforce a negative lookbehind to wrangle ceph-mons

- lib/charms/nrpe_exporter/v0/nrpe_exporter.py
- pyproject.toml
- tests/unit/test_charm.py
- tox.ini
The **flake8** plugins we use are re-implemented in **ruff**, which is why they have been removed from the dependencies.
**isort** is enabled (and used when formatting) through the `I001` rule.
The "exclude list" has been updated to omit folders that **ruff** excludes by default.
Everything else is the same, the only difference being two new rules being ignored (which weren't check before anyway): 
* `W605: Invalid escape sequence`, as it wasn't recognizing raw strings for some reason;
* `RET504: Unnecessary variable assignment before return statement`, which we do everywhere as it increases readability.
> use ruff instead of flake8

- lib/charms/nrpe_exporter/v0/nrpe_exporter.py
- lib/charms/vector/v0/vector.py
This **might** resolve #70, as it will divide the metric ingestion rate by 60 for internal metrics and by 4 for host metrics, giving Vector plenty of time to garbage collect and flush the metrics to the prometheus_exporter sink.
The default for scraping internal metrics and host metrics in Vector is every second for internal metrics and every 15 seconds for host metrics. This is **way** to excessive and creates pressure on Prometheus.
Change the interval to every minute for both. 
Deploy it and make sure metrics come in at the expected interval.
Scrape internal metrics and host metrics more sparingly.
> scrape internal metrics and host metrics more sparingly

- lib/charms/nrpe_exporter/v0/nrpe_exporter.py
Closes #73.
The `alerts` variable name was used both for the collection of final NRPE alerts and for the single alerts generated by `_generate_data()`.
> fix updating alerts in stored state

- lib/charms/grafana_k8s/v0/grafana_dashboard.py
- lib/charms/operator_libs_linux/v1/systemd.py
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
Closes #72.
As explained in detail in https://github.com/canonical/prometheus-k8s-operator/pull/507, this PR removes unused failing code from cos-proxy.
**Additional changes**: `charmcraft fetch-lib`.
> stop cos-proxy from HTTP scraping NRPE endpoints

- src/charm.py
When `_on_nrpe_targets_changed` is called with no event arg (event=None), the nrpes variable cannot be init'ed from it.
Fixes #92.
> Fix nrpes var init

- .gitignore
- README.md
- metadata.yaml
- src/charm.py
- tests/unit/test_relation_monitors.py
When nrpe changed prefix, cos-proxy failed to correctly calculate the current list of targets, keeping stale rows in the file.
Make sure stale targets are not kept, by correctly looking up entries in the csv.
Fixes #93.
> Do not keep stale targets in csv file

- lib/charms/nrpe_exporter/v0/nrpe_exporter.py
- src/charm.py
As part of #89, we now update stored state only after relation data.
But emission of custom events is [nested, not queued](https://github.com/canonical/operator/issues/1070).
Due to the code ordering in the charm, the custom event handler was getting data from stored state that was't updated yet.
Add "current alerts" to the lib's event data so that charm code won't need to fetch it from stored state.
Fixes #99.
Note that cos-proxy adheres very strongly to delta-charming. As a result, upgrading the charm to this revision will not resolve the issues described in #99.
I imagine that only a rewrite of key handlers to be holistic would help with resolving gaps on upgrade.
I confirmed the issue and the fix using the following bundle.
- scale up/down the ubuntu charm
- add/remove the glance …
> Add `current_alerts` to `NrpeTargetsChangedEvent`

- src/charm.py
- tests/unit/test_relation_monitors.py
The nrpe targets changed event hook is sometimes called without an event arg. In such cases we cannot obtain alerts from `event` attributes.
Obtain alerts from stored state. This is the same as #94, but follows-up #100.
Fixes #102.
See newly added utest. Before this change, the utest would fail with the same error reported in #102.
> Fix alerts assignment when event is None

- src/charm.py
- tests/unit/test_relation_monitors.py
- tox.ini
Some units are stuck in blocked `Missing one of (Prometheus|target|nrpe) relation(s)`, even though all relations are in fact in place.
Set `_stored.have_prometheus = True` only after updating relation data. Related to #89. Addresses #105.
Drive-by fixes:
- Append instead of overwriting "missing relation" status messages.
```
juju refresh --switch cos-proxy --channel=edge/108 cos-proxy-monitors  # Expires at 2024-02-04T00:00:00Z
```
Deploy the k8s bundle in a k8s model and the lxd bundle in a lxd model
```
$ juju deploy --trust ./k8s-bundle.yaml  # on k8s model
$ juju deploy ./lxd-bundle.yaml  # on lxd model
```
```yaml
bundle: kubernetes
applications:
prom:
charm: prometheus-k8s
channel: edge
revision: 163
resources:
prometheus-image: 136
scale: 1
trust: true
--- # overlay.yaml …
```
> Update stored state after relation data

- lib/charms/vector/v0/vector.py
#112 
Add a keepalive to the logstash source so that if it doesn't receive a packet for one hour, it will drop the connection and free the resources.
Mostly the same instructions as described on #112 - Just verify that the connections are dropped.
> Add keepalive to logstash source

- lib/charms/nrpe_exporter/v0/nrpe_exporter.py
- tests/scenario/test_alerts.py
#117 introduced a regression where hostnames without unit id were assumed to be an error, which breaks compatibility with nrpe running on physical servers and VMs.
Restore to the previous "blind" `re.sub` instead of raising with `re.match`.
Revision 62 of 'cos-proxy' released to `edge/pr-120`.
Fixes #119.
> Allow hostnames without unit id

- charmcraft.yaml
- src/charm.py
Incorrect machine name for nrpe binary.
Hard-code machine names.
Fixes #124.
Make sure the follow bundle deploys with no errors:
```yaml
series: jammy
applications:
cp:
charm: ./cos-proxy_ubuntu-20.04-amd64_ubuntu-22.04-amd64.charm
num_units: 1
nrpe:
charm: nrpe
channel: edge
revision: 117
ub:
charm: ubuntu
channel: edge
revision: 24
num_units: 1
relations:
- - cp:monitors
- nrpe:monitors
- - nrpe:general-info
- ub:juju-info
```
Normal procedure.
> Fix machine name handling for nrpe_exporter binary

- lib/charms/grafana_agent/v0/cos_agent.py
- requirements.txt
COS Proxy isn't being release due to a pydantic [version mismatch](https://github.com/canonical/cos-proxy-operator/actions/runs/8156730592/job/22294841050)
> Pydantic version bump

- requirements.txt
- tests/scenario/helpers.py
- tests/scenario/test_charm.py
- tests/unit/test_charm.py
Closes #140 
The prometheus_scrape schema includes an optional field for `metrics_path`.  Pydantic's semantics for how a field is marked as "optional" changed between v1 and v2, resulting in Pydantic v2 erroneously interpreting the `metrics_path` field as required.  [This PR in charm-relation-interfaces](https://github.com/canonical/charm-relation-interfaces/pull/154) updates the schema to use the pydantic v2 way of defining optional attributes.  The current PR updates our dependencies to use this fixed schema.  
Also included here is a conversion of a unit test to scenario in order to reproduce the above issue.  The previous unit test conceptually should have caught this bug, but because the issue occurred when calling `._get_scrape_configs()` (which is only called in `__init__`) unit …
> update charm-relation-interfaces to use prometheus_scrape schema that is compatible with pydantic v2

- requirements.txt
- src/charm.py
- tests/unit/test_charm.py
- tests/unit/test_relation_monitors.py
Status is set to Blocked unnecessarily.
Use the [mandatory relation pairs helper](https://github.com/canonical/cos-lib/pull/25).
Fixes #144.
See unit tests.
> Fix status for missing relations

- charmcraft.yaml
- tox.ini
When we build pyyaml from source, we don't get the C-optimized lib.
As a result, ops serialization is slow.
Use the binary version.
Serialization is 20x faster.
Addresses #56.
- https://github.com/pengwyn/charm-relation-test/pull/2
- https://matrix.to/#/!xdClnUGkurzjxqiQcN:ubuntu.com/$6u1oVcoGibWOg7RkIflLFvfqqHLetfCIwksh7gMli9M?via=ubuntu.com&via=matrix.org
> Use a binary PyYAML package

- INTEGRATING.md
- tests/manual/topologies/README.md
- tests/manual/topologies/cos-proxy-SAAS-bundle.yaml
- tests/manual/topologies/cos-proxy-gagent-bundle.yaml
`cos-proxy` is lacking deployment diagrams, as well as a description of what relations need/should be hooked, and in what manner.
> Improve COS Proxy deployment documentation

- lib/charms/grafana_agent/v0/cos_agent.py
- lib/charms/grafana_k8s/v0/grafana_dashboard.py
- lib/charms/nrpe_exporter/v0/nrpe_exporter.py
- tests/unit/test_relation_monitors.py
This PR solves #151
- Run unit tests
- Manually:
- Follow instructions "To Reproduce" in issue to deploy.
- Upgrade `cos-proxy-operator` with a charm built with this PR
- `juju deploy cos-proxy --channel edge/pr153 --base=ubuntu@22.04`
- `juju deploy cos-proxy --channel edge/pr153 --base=ubuntu@20.04`
- Verify in Prometheus that nagios_host_context is not present in alert rules.
> Avoid adding nagios_host_context to juju_unit and juju_application in Alert rules

- charmcraft.yaml
#153 [failed](https://github.com/canonical/cos-proxy-operator/actions/runs/10320770813/job/28572368296) to release because of pack issue.
Add rust to build-packages, similar to https://github.com/canonical/alertmanager-k8s-operator/pull/281.
Drive-by: address deprecation warning:
```
CRAFT_TARGET_ARCH is deprecated, use CRAFT_ARCH_BUILD_FOR
```
> Add rust to build packages

- lib/charms/nrpe_exporter/v0/nrpe_exporter.py
This is so that the severity label is always set. Else PagerDuty's API fails to send the notification when the average is transitioning between integers, and it causes the AlertmanagerNotificationsFailed alert to fire.
Incidentally, it makes no sense to have the result of an NRPE check to be non-integer, so that shakes that confusing bit off too.
> Round the result of avg_over_time

- charmcraft.yaml
- lib/charms/grafana_agent/v0/cos_agent.py
- lib/charms/nrpe_exporter/v0/nrpe_exporter.py
- lib/charms/operator_libs_linux/v0/apt.py
- tests/interface/conftest.py
- tests/scenario/test_alerts.py
- tests/scenario/test_charm.py
- tests/unit/test_charm.py
- tests/unit/test_relation_monitors.py
- tox.ini
This PR fixes: https://github.com/canonical/cos-proxy-operator/issues/146
We multiply the value  by 2 so the severity is mapped to a critical
1. Create a k8s model and deploy `cos-lite` in it
2. Offer the `prometheus-scrape` interface: `juju offer prometheus:metrics-endpoint prometheus-scrape`
3. Create a machine model
4. Consume the `prometheus-scrape` offer: `juju consume microk8s:admin/cos.prometheus-scrape`
6.  Deploy this bundle:
```yaml
default-base: ubuntu@22.04/stable
saas:
grafana-dashboards:
url: microk8s:admin/cos.grafana-dashboards
loki-logging:
url: microk8s:admin/cos.loki-logging
prometheus-receive-remote-write:
url: microk8s:admin/cos.prometheus-receive-remote-write
prometheus-scrape:
url: microk8s:admin/cos.prometheus-scrape
applications:
cos-proxy:
charm: …
```
> Fix mapped severity
